#!/usr/bin/env bash

sleep 5 && wlr-randr --output SPI-1 --custom-mode 480x320@10 &

/usr/bin/cage -- \
  /usr/bin/chromium \
    --start-fullscreen \
    'http://localhost:8443/client/galene/robot.html'

exit $?
